version: 0.0
Resources:
  - testrepo:
      Type: AWS::Lambda::Function
      Properties:
        Name: "testrepo"
        Alias: "testrepoAlias"
        CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
  - BeforeAllowTraffic: "lambda.function"
  - AfterAllowTraffic: "lambda.function"